//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AlbumOnlineApp.com.somee.albumonline2023 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AlbumSWSoap", Namespace="http://tempuri.org/")]
    public partial class AlbumSW : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddImgOperationCompleted;
        
        private System.Threading.SendOrPostCallback get_photosOperationCompleted;
        
        private System.Threading.SendOrPostCallback AspUserLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback addAspNetUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AlbumSW() {
            this.Url = "http://albumonline2023.somee.com/AlbumOnline/AlbumSW.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddImgCompletedEventHandler AddImgCompleted;
        
        /// <remarks/>
        public event get_photosCompletedEventHandler get_photosCompleted;
        
        /// <remarks/>
        public event AspUserLoginCompletedEventHandler AspUserLoginCompleted;
        
        /// <remarks/>
        public event addAspNetUserCompletedEventHandler addAspNetUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddImg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddImg([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] img, int tipo, string user) {
            object[] results = this.Invoke("AddImg", new object[] {
                        img,
                        tipo,
                        user});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddImgAsync(byte[] img, int tipo, string user) {
            this.AddImgAsync(img, tipo, user, null);
        }
        
        /// <remarks/>
        public void AddImgAsync(byte[] img, int tipo, string user, object userState) {
            if ((this.AddImgOperationCompleted == null)) {
                this.AddImgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddImgOperationCompleted);
            }
            this.InvokeAsync("AddImg", new object[] {
                        img,
                        tipo,
                        user}, this.AddImgOperationCompleted, userState);
        }
        
        private void OnAddImgOperationCompleted(object arg) {
            if ((this.AddImgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddImgCompleted(this, new AddImgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_photos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SWPhoto[] get_photos(string user) {
            object[] results = this.Invoke("get_photos", new object[] {
                        user});
            return ((SWPhoto[])(results[0]));
        }
        
        /// <remarks/>
        public void get_photosAsync(string user) {
            this.get_photosAsync(user, null);
        }
        
        /// <remarks/>
        public void get_photosAsync(string user, object userState) {
            if ((this.get_photosOperationCompleted == null)) {
                this.get_photosOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_photosOperationCompleted);
            }
            this.InvokeAsync("get_photos", new object[] {
                        user}, this.get_photosOperationCompleted, userState);
        }
        
        private void Onget_photosOperationCompleted(object arg) {
            if ((this.get_photosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_photosCompleted(this, new get_photosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AspUserLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AspUserLogin(string user, string pass) {
            object[] results = this.Invoke("AspUserLogin", new object[] {
                        user,
                        pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AspUserLoginAsync(string user, string pass) {
            this.AspUserLoginAsync(user, pass, null);
        }
        
        /// <remarks/>
        public void AspUserLoginAsync(string user, string pass, object userState) {
            if ((this.AspUserLoginOperationCompleted == null)) {
                this.AspUserLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAspUserLoginOperationCompleted);
            }
            this.InvokeAsync("AspUserLogin", new object[] {
                        user,
                        pass}, this.AspUserLoginOperationCompleted, userState);
        }
        
        private void OnAspUserLoginOperationCompleted(object arg) {
            if ((this.AspUserLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AspUserLoginCompleted(this, new AspUserLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addAspNetUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addAspNetUser(string Email, string Pass) {
            object[] results = this.Invoke("addAspNetUser", new object[] {
                        Email,
                        Pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addAspNetUserAsync(string Email, string Pass) {
            this.addAspNetUserAsync(Email, Pass, null);
        }
        
        /// <remarks/>
        public void addAspNetUserAsync(string Email, string Pass, object userState) {
            if ((this.addAspNetUserOperationCompleted == null)) {
                this.addAspNetUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddAspNetUserOperationCompleted);
            }
            this.InvokeAsync("addAspNetUser", new object[] {
                        Email,
                        Pass}, this.addAspNetUserOperationCompleted, userState);
        }
        
        private void OnaddAspNetUserOperationCompleted(object arg) {
            if ((this.addAspNetUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addAspNetUserCompleted(this, new addAspNetUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SWPhoto {
        
        private int idField;
        
        private byte[] imgField;
        
        private string userField;
        
        private string fechaField;
        
        private int tipoIdField;
        
        private string statusField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Img {
            get {
                return this.imgField;
            }
            set {
                this.imgField = value;
            }
        }
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public int TipoId {
            get {
                return this.tipoIdField;
            }
            set {
                this.tipoIdField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddImgCompletedEventHandler(object sender, AddImgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddImgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddImgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void get_photosCompletedEventHandler(object sender, get_photosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_photosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal get_photosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SWPhoto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SWPhoto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AspUserLoginCompletedEventHandler(object sender, AspUserLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AspUserLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AspUserLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void addAspNetUserCompletedEventHandler(object sender, addAspNetUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addAspNetUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addAspNetUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591